name = "hmb-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# Configuration KV Namespace pour stocker les abonnés
kv_namespaces = [
  { binding = "SUBSCRIBERS", id = "24a58d372bd945e786f22d47c84c278c" }
]

[vars]
GMAIL_USER = "hmb05092006@gmail.com"

# Configuration de l'environnement de développement
[env.development]
workers_dev = true

# Configuration de l'environnement de production
[env.production]
workers_dev = true  # Changé à true pour utiliser workers.dev